profile:
    # dataset: cnc_toolwear
    dataset:
    - cnc-mill-tool-wear
    - cnc-meta

clean:
    # target: X1_ActualPosition
    target: tool_condition
    classification: True
    onehot_encode_target: False
    combine_files: True
    percentage_zeros_threshold: 1.0
    input_max_correlation_threshold: 1.0
    correlation_metric: pearson

featurize:
    features:
        - X1_ActualPosition
        - X1_ActualVelocity
        - X1_ActualAcceleration
        - X1_CommandPosition
        - X1_CommandVelocity
        - X1_CommandAcceleration
        - X1_CurrentFeedback
        - X1_DCBusVoltage
        - X1_OutputCurrent
        - X1_OutputVoltage
        - X1_OutputPower
        - Y1_ActualPosition
        - Y1_ActualVelocity
        - Y1_ActualAcceleration
        - Y1_CommandPosition
        - Y1_CommandVelocity
        - Y1_CommandAcceleration
        - Y1_CurrentFeedback
        - Y1_DCBusVoltage
        - Y1_OutputCurrent
        - Y1_OutputVoltage
        - Y1_OutputPower
        - Z1_ActualPosition
        - Z1_ActualVelocity
        - Z1_ActualAcceleration
        - Z1_CommandPosition
        - Z1_CommandVelocity
        - Z1_CommandAcceleration
        - S1_ActualPosition
        - S1_ActualVelocity
        - S1_ActualAcceleration
        - S1_CommandPosition
        - S1_CommandVelocity
        - S1_CommandAcceleration
        - S1_CurrentFeedback
        - S1_DCBusVoltage
        - S1_OutputCurrent
        - S1_OutputVoltage
        - S1_OutputPower
    add_rolling_features: False
    rolling_window_size: 100
    remove_features:
        # - feature1
        # - feature2
        # - Axis_Y_Position_Diff
        # - Axis_Z_Position_Diff
        # - Axis_B_Position_Diff
        # - Abs_Sum_Position_Diff

    target_min_correlation_threshold: 0.0

split:
    train_split: 0.7
    shuffle_files: False
    calibrate_split: 0.0

scale:
    input: minmax
    output: minmax

sequentialize:
    window_size: 1
    overlap: 0
    target_size: 10
    shuffle_samples: False
    future_predict: False

train:
    learning_method: dt
    n_epochs: 50
    batch_size: 256
    kernel_size: 5
    early_stopping: True
    patience: 40

evaluate:
    explainable_data_point: 1
